Books\Domain\Model\Book\Book:
    type: entity
    table: BOOKS
    repositoryClass: Books\DomainBundle\Ports\Adapter\Persistance\Doctrine\Book\BookRepository
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: id
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            nullable: false
            comment: ''
            column: title
    oneToMany:
        lectures:
            targetEntity: Books\Domain\Model\Lectures\Lecture
            mappedBy: book
