web:
    resource: "@WebBundle/Resources/config/routing.yml"
    prefix:   /

domain_core:
    resource: "@DomainBundle/Resources/config/routing.yml"
    prefix:   /

contacto_default:
    path: /help/{pagina}
    defaults: {_controller: WebBundle:Help:index}

portada:
    path: /
    defaults: {_controller: WebBundle:Default:index}