parameters:
#    domain_core.example.class: Books\DomainBundle\Example

services:
#    domain_core.example:
#        class: %domain_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
